-- V14__password_reset_tokens.sql
-- Single-use, time-boxed tokens generated by an admin for a user who
-- needs to rotate their password. The hash (never the plaintext) is
-- stored server-side; consuming the token is an atomic UPDATE under
-- the unique index.

CREATE TABLE password_reset_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL
                    REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(128) NOT NULL,
    issued_by   UUID         NOT NULL
                    REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT password_reset_tokens_hash_unique UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);
