-- V9__seed_exercises.sql
-- Bilingual (TR + EN) seed for the exercises catalog. 50 entries grouped
-- by equipment so the /api/exercises?equipment=... filter produces
-- meaningful "home equipment only" views out of the box.
--
-- All media URLs are NULL on purpose; images and videos are uploaded
-- via the admin UI (or pasted as external URLs) in PHASE 5.
--
-- This seed is idempotent: it checks name_en before inserting so running
-- Flyway a second time against a populated DB is a no-op.

INSERT INTO exercises (
    id, name_tr, name_en, category, equipment, muscle_primary, muscle_secondary,
    description_tr, description_en,
    form_tips_tr, form_tips_en,
    common_mistakes_tr, common_mistakes_en,
    difficulty)
SELECT v.* FROM (VALUES
-- ---- BODYWEIGHT (1-20) ----
(gen_random_uuid(), 'Sinav', 'Push-up', 'push', 'bodyweight', 'chest', 'triceps, shoulders',
 'Klasik sinav. Govde duz, elleri omuz genisliginde, bel cukurlasmadan iner ve cikar.',
 'Classic push-up. Straight body, hands shoulder-width, lower until chest nearly touches, press back up.',
 ARRAY['Govdeyi sik tut','Dirsekler govde ile 45 derece','Omurga notr kalsin'],
 ARRAY['Keep core braced','Elbows 45 degrees to the body','Spine neutral throughout'],
 ARRAY['Bel sarkiyor','Dirsekler tamamen aciliyor'],
 ARRAY['Hips sagging','Elbows flaring out'],
 'beginner'),
(gen_random_uuid(), 'Diz Sinav', 'Knee Push-up', 'push', 'bodyweight', 'chest', 'triceps',
 'Dizler yerde klasik sinav. Tam sinava hazirlik icin ideal.',
 'Push-up from the knees; a scaled version useful for building up to a full push-up.',
 ARRAY['Dizden omuza duz hat','Kalca asagi dusmesin','Dirsek kontrolu'],
 ARRAY['Knee to shoulder straight line','Hips stay aligned','Control the eccentric'],
 ARRAY['Kalca yukseliyor','Dirsek savrulmasi'],
 ARRAY['Hips pike','Elbow flare'],
 'beginner'),
(gen_random_uuid(), 'Egimli Sinav', 'Incline Push-up', 'push', 'bodyweight', 'chest', 'triceps',
 'Eller bir masa veya duvara dayali yapilan sinav. Acinin egimi duser, yuk hafifler.',
 'Hands on a bench, table or wall. Easier than floor push-up as the angle shifts load.',
 ARRAY['Yuzey sabit olmali','Dirsekleri kilitleme','Govdeyi sik tut'],
 ARRAY['Use a stable surface','Do not lock elbows','Brace the core'],
 ARRAY['Yuzey kayiyor','Kalca dusuyor'],
 ARRAY['Surface slipping','Hips dropping'],
 'beginner'),
(gen_random_uuid(), 'Plank', 'Plank', 'core', 'bodyweight', 'core', NULL,
 'On kollar yerde, govde tepeden topuga duz hat. Karin ve kalca sikilasir.',
 'Forearms down, body straight from head to heels; brace abs and glutes.',
 ARRAY['Kalcayi squeez et','Omuz dirsegin uzerinde','Nefes al'],
 ARRAY['Squeeze glutes','Shoulders over elbows','Keep breathing'],
 ARRAY['Bel cokuyor','Kalca yukseliyor'],
 ARRAY['Low back sag','Hips too high'],
 'beginner'),
(gen_random_uuid(), 'Yan Plank', 'Side Plank', 'core', 'bodyweight', 'obliques', 'shoulders',
 'Yan duzlemde tek dirsek ve yan ayakla destek. Yan karin kaslarini hedefler.',
 'Side-lying forearm and foot support; targets the obliques.',
 ARRAY['Kalca yukaryida','Omuz dirsegin uzerinde','Govde tek hatta'],
 ARRAY['Lift hips high','Shoulder stacked over elbow','Keep body in one line'],
 ARRAY['Kalca dusuyor','Omuz icine cokmus'],
 ARRAY['Hips dropping','Shoulder sinking'],
 'beginner'),
(gen_random_uuid(), 'Olu Bocek', 'Dead Bug', 'core', 'bodyweight', 'core', 'hip flexors',
 'Sirt ustu, zit kol ve bacak uzanir, bel dayanir. Anti-extension core calismasi.',
 'On your back, alternate extending opposite arm and leg while pressing low back into floor.',
 ARRAY['Bel yere yapisik','Yavas temp','Nefesi birak'],
 ARRAY['Lumbar spine pinned','Slow tempo','Exhale on extension'],
 ARRAY['Bel bosluk birakiyor','Cok hizli'],
 ARRAY['Lower back lifting','Rushing reps'],
 'beginner'),
(gen_random_uuid(), 'Kus Kopegi', 'Bird Dog', 'core', 'bodyweight', 'core', 'lower back',
 'Dort ayak pozisyondan zit kol bacak uzar. Bel stabilitesini kurar.',
 'From quadruped, extend opposite arm and leg. Trains anti-rotation and spinal stability.',
 ARRAY['Kalca ve sirt sabit','Uzatirken yavas','Karin sikili'],
 ARRAY['Hips and back stay still','Slow extension','Abs engaged'],
 ARRAY['Kalca donuyor','Bel cokmus'],
 ARRAY['Hip rotation','Low back dipping'],
 'beginner'),
(gen_random_uuid(), 'Kopru', 'Glute Bridge', 'legs', 'bodyweight', 'glutes', 'hamstrings',
 'Sirt ustu yat, dizleri buk, kalcayi tavana dogru kaldir. Kalca ve arka bacagi calisir.',
 'Lie on back, bend knees, drive hips up; targets glutes and hamstrings.',
 ARRAY['Topuktan it','Kalcayi sik','Dizler paralel'],
 ARRAY['Drive through heels','Squeeze glutes at top','Keep knees parallel'],
 ARRAY['Bel zorlaniyor','Diz ice cokuyor'],
 ARRAY['Overarching the back','Knees caving in'],
 'beginner'),
(gen_random_uuid(), 'Vucut Agirligi Squat', 'Bodyweight Squat', 'legs', 'bodyweight', 'quads', 'glutes',
 'Ayaklar omuz genisliginde, kalca geri otur. Dizler parmak istikametinde.',
 'Feet shoulder-width, hips sit back, knees track over toes.',
 ARRAY['Kalca geri','Dizler parmaga bak','Gogus yukari'],
 ARRAY['Hips back first','Knees track over toes','Chest up'],
 ARRAY['Dizler ice duser','Topuk kalkiyor'],
 ARRAY['Knee valgus','Heels lifting'],
 'beginner'),
(gen_random_uuid(), 'Hamle', 'Lunge', 'legs', 'bodyweight', 'quads', 'glutes',
 'One adim at, arka diz yere yakin iner. Tek bacakta on gruplari calisir.',
 'Step forward, lower until back knee near floor. Unilateral quad and glute work.',
 ARRAY['On diz 90 derece','Govde dik','Dizle topuk aligned'],
 ARRAY['Front knee ~90 degrees','Torso vertical','Knee stacked over ankle'],
 ARRAY['On diz one tasiyor','Govde egik'],
 ARRAY['Front knee past toes','Torso leaning'],
 'beginner'),
(gen_random_uuid(), 'Geri Hamle', 'Reverse Lunge', 'legs', 'bodyweight', 'quads', 'glutes',
 'Arkaya adim atarak yapilan hamle. Diz baskisi daha az, kalca daha aktif.',
 'Stepping backward; less knee stress, more glute recruitment than forward lunge.',
 ARRAY['Govde dik','On topuga yuklen','Karin sikili'],
 ARRAY['Keep torso upright','Drive through front heel','Brace core'],
 ARRAY['Govde one yatiyor','Denge kaybi'],
 ARRAY['Forward torso lean','Balance loss'],
 'beginner'),
(gen_random_uuid(), 'Duvar Oturusu', 'Wall Sit', 'legs', 'bodyweight', 'quads', NULL,
 'Sirt duvarda, kalca 90 derecede hayali sandalyede otur. Izometrik dayaniklilik.',
 'Back on wall, hips at 90 degrees in an imaginary chair. Isometric quad endurance.',
 ARRAY['Dizler 90 derece','Topuk altinda','Sirt duvar temas'],
 ARRAY['Knees at 90','Heels under knees','Back flush to wall'],
 ARRAY['Topuk kalkiyor','Kalca asagi kayiyor'],
 ARRAY['Heels lifting','Hips sliding'],
 'beginner'),
(gen_random_uuid(), 'Rus Donmesi', 'Russian Twist', 'core', 'bodyweight', 'obliques', NULL,
 'Oturarak bacaklari kaldir, govdeyi saga sola cevir. Yan karin calismasi.',
 'Seated, feet elevated, rotate torso side to side. Targets obliques.',
 ARRAY['Sirti duz tut','Yavas ve kontrollu','Govdeden don'],
 ARRAY['Flat back','Slow controlled rotation','Rotate from torso'],
 ARRAY['Yuvarlanan sirt','Kol savurma'],
 ARRAY['Rounded back','Arm swinging'],
 'intermediate'),
(gen_random_uuid(), 'Bisiklet Karin', 'Bicycle Crunch', 'core', 'bodyweight', 'abs', 'obliques',
 'Sirt ustu, dirsek zit dize dokunur seklinde bisiklet hareketi.',
 'Lying down, alternate elbow-to-opposite-knee in a cycling motion.',
 ARRAY['Bel yere yapisik','Kontrollu tempo','Boyun rahat'],
 ARRAY['Lumbar stays down','Controlled tempo','Relaxed neck'],
 ARRAY['Bel kaldirma','Boyun zorlanmasi'],
 ARRAY['Low back lifting','Neck strain'],
 'beginner'),
(gen_random_uuid(), 'Burpee', 'Burpee', 'cardio', 'bodyweight', 'full body', NULL,
 'Ayakta dur, squat, plank, sinav, ziplama siklusu. Tam vucut kardiyo.',
 'Stand, squat, plank, push-up, jump back up. Full-body conditioning.',
 ARRAY['Plankta govde duz','Iniste kontrol','Tempo sabit'],
 ARRAY['Solid plank','Controlled descent','Steady tempo'],
 ARRAY['Bel cokmus plank','Cok hizli'],
 ARRAY['Sagging plank','Rushing'],
 'intermediate'),
(gen_random_uuid(), 'Dag Tirmanisi', 'Mountain Climbers', 'cardio', 'bodyweight', 'core', 'legs',
 'Plank pozisyonda dizleri sirayla gogse dogru cek. Kardiyo ve core.',
 'From plank, drive knees to chest alternately. Core and cardio.',
 ARRAY['Kalca sabit','Omuz bilek aligned','Nefes ritmik'],
 ARRAY['Stable hips','Shoulders over wrists','Rhythmic breathing'],
 ARRAY['Kalca yukseliyor','Ayak surunmesi'],
 ARRAY['Hips hiking','Feet scraping'],
 'beginner'),
(gen_random_uuid(), 'Jumping Jack', 'Jumping Jacks', 'cardio', 'bodyweight', 'full body', NULL,
 'Ziplarken kollari ustten cirp, bacaklari ac kapat. Isinma klassigi.',
 'Jump while spreading legs and raising arms overhead. Classic warm-up.',
 ARRAY['Yumusak inis','Ritmi koru','Omuz rahat'],
 ARRAY['Soft landing','Steady rhythm','Relaxed shoulders'],
 ARRAY['Sert inis','Dizler kilitli'],
 ARRAY['Hard landing','Locked knees'],
 'beginner'),
(gen_random_uuid(), 'Negatif Cekis', 'Negative Pull-up', 'pull', 'bodyweight', 'back', 'biceps',
 'Ustten baslayip yavasca asagi in. Tam pull-up icin yol acar.',
 'Start at the top and lower slowly; builds strength toward a full pull-up.',
 ARRAY['3-5 saniye inis','Skapulayi retract','Gerginlik kaybolmasin'],
 ARRAY['3-5 second descent','Retract scapula','Stay tense'],
 ARRAY['Serbest birakma','Omuz yukselmis'],
 ARRAY['Dropping','Shoulders shrugged'],
 'intermediate'),
(gen_random_uuid(), 'Olu Asi', 'Dead Hang', 'pull', 'bodyweight', 'forearms', 'shoulders',
 'Baradan asili kal. Kavrama ve omuz dayanikliligi.',
 'Passive hang from a bar. Grip strength and shoulder endurance.',
 ARRAY['Omuzlari aktif tut','Nefes al','Govde sakin'],
 ARRAY['Active shoulders','Breathe steadily','Calm torso'],
 ARRAY['Omuz tamamen gevsek','Sallama'],
 ARRAY['Fully relaxed shoulders','Body swinging'],
 'beginner'),
(gen_random_uuid(), 'Pike Sinav', 'Pike Push-up', 'push', 'bodyweight', 'shoulders', 'triceps',
 'Kalca havada ters-V pozisyonunda sinav. Omuz baskisi taklidi.',
 'Pike position with hips high; push-up variant that trains shoulders.',
 ARRAY['Kalca yukari','Bas elle hizali','Dirsek kontrol'],
 ARRAY['Hips high','Head between hands','Controlled elbows'],
 ARRAY['Kalca dusuk','Boyun zorlanmasi'],
 ARRAY['Hips low','Neck strain'],
 'intermediate'),
-- ---- DUMBBELL (21-38) ----
(gen_random_uuid(), 'Dumbbell Omuz Baski', 'Dumbbell Shoulder Press', 'push', 'dumbbell', 'shoulders', 'triceps',
 'Oturur veya ayakta dumbbell ile bas ustune baski. Omuz gelistirir.',
 'Seated or standing, press dumbbells overhead. Builds shoulder mass.',
 ARRAY['Bilek duz','Karin sikili','Yukarida kilitleme'],
 ARRAY['Neutral wrists','Brace core','Avoid full lockout'],
 ARRAY['Bel cukurlasiyor','Dirsek tam kilitli'],
 ARRAY['Overarching','Full elbow lock'],
 'intermediate'),
(gen_random_uuid(), 'Yerde Dumbbell Bench', 'Floor Dumbbell Press', 'push', 'dumbbell', 'chest', 'triceps',
 'Yerde sirtustu yatarak dumbbell gogus baskisi. Omuz korumali varyasyon.',
 'Lying supine on the floor, press dumbbells; shoulder-friendly bench alternative.',
 ARRAY['Dirsek yere 45 derece','Skapulayi geri cek','Kontrollu eksantrik'],
 ARRAY['Elbows ~45 to body','Retract shoulder blades','Controlled eccentric'],
 ARRAY['Dirsekler tam aciyor','Bel cokmus'],
 ARRAY['Elbows flaring','Lumbar sagging'],
 'intermediate'),
(gen_random_uuid(), 'Yanal Kaldirma', 'Lateral Raise', 'push', 'dumbbell', 'lateral deltoid', NULL,
 'Dumbbell ile kollari yanlardan omuz hizasina kaldir. Yan omuzu hedefler.',
 'Lift dumbbells to shoulder height from the sides. Isolates the lateral delts.',
 ARRAY['Hafif dirsek bukumu','Baspermekter asagi','Tempo kontrol'],
 ARRAY['Slight elbow bend','Thumbs slightly down','Controlled tempo'],
 ARRAY['Cok agir secim','Govde sallamasi'],
 ARRAY['Too heavy','Body swing'],
 'beginner'),
(gen_random_uuid(), 'One Kaldirma', 'Front Raise', 'push', 'dumbbell', 'anterior deltoid', NULL,
 'Dumbbelllari onde omuz hizasina kaldir. On omuz calistirmasi.',
 'Raise dumbbells in front to shoulder height. Front delt isolation.',
 ARRAY['Govde sabit','Hafif dirsek bukumu','Yavas iniy'],
 ARRAY['Stable torso','Slight elbow bend','Slow lowering'],
 ARRAY['Govde savrulmasi','Asiri yukselme'],
 ARRAY['Torso swing','Going too high'],
 'beginner'),
(gen_random_uuid(), 'Arka Omuz Fly', 'Rear Delt Fly', 'pull', 'dumbbell', 'rear deltoid', 'traps',
 'One egil, dumbbelllari yana acarak arka omuzu calistir.',
 'Bent-over, open arms wide to hit the rear deltoids.',
 ARRAY['Govde 45 derece','Skapulayi squeeze','Dirsek sabit aciyla'],
 ARRAY['Hinge ~45','Squeeze shoulder blades','Fixed elbow angle'],
 ARRAY['Govde dogruluyor','Asiri agir'],
 ARRAY['Standing up mid-rep','Too heavy'],
 'intermediate'),
(gen_random_uuid(), 'Triceps Kickback', 'Tricep Kickback', 'push', 'dumbbell', 'triceps', NULL,
 'Govde one egik, dirsek sabit, dumbbelli arkaya aciyor. Triceps izolasyonu.',
 'Torso hinged, elbow fixed, extend dumbbell backward. Triceps isolation.',
 ARRAY['Dirsek govde yanina kilit','Ust kol hareketsiz','Peak sik'],
 ARRAY['Elbow pinned to side','Upper arm still','Squeeze at top'],
 ARRAY['Dirsek dusmesi','Govde burkulmasi'],
 ARRAY['Elbow dropping','Torso twisting'],
 'intermediate'),
(gen_random_uuid(), 'Ense Uzerine Triceps Extension', 'Overhead Tricep Extension', 'push', 'dumbbell', 'triceps', NULL,
 'Tek dumbbelli iki elle bas ustunde tut, ensenin arkasina indir-cikart.',
 'Hold one dumbbell overhead with both hands, lower behind head, press up.',
 ARRAY['Dirsek sabit','Kulak yanindan gecsin','Bel kilit'],
 ARRAY['Elbows stationary','Move past ears','Lock lumbar'],
 ARRAY['Dirsek aciliyor','Bel cukurlasiyor'],
 ARRAY['Elbows flaring','Hyperextended back'],
 'intermediate'),
(gen_random_uuid(), 'Cekic Curl', 'Hammer Curl', 'pull', 'dumbbell', 'brachialis', 'forearms',
 'Bilekler notr dumbbell curl. Cekic tutusu brachialisi hedefler.',
 'Curl with neutral grip; hammer grip hits brachialis.',
 ARRAY['Dirsek govdede','Bilek duz','Kontrollu iniy'],
 ARRAY['Elbows pinned','Wrist neutral','Slow descent'],
 ARRAY['Omuz itmesi','Govde swing'],
 ARRAY['Shoulder push','Torso swing'],
 'beginner'),
(gen_random_uuid(), 'Dumbbell Biceps Curl', 'Dumbbell Bicep Curl', 'pull', 'dumbbell', 'biceps', 'forearms',
 'Supine tutusla klasik biceps curl. Hafifle baslayip kontrolde yukselt.',
 'Standard supinated bicep curl. Start light, lift with control.',
 ARRAY['Dirsek pivot','Bilek sabit','Tam ROM'],
 ARRAY['Elbow as pivot','Stable wrist','Full ROM'],
 ARRAY['Govde sallamasi','Yarim ROM'],
 ARRAY['Body English','Half reps'],
 'beginner'),
(gen_random_uuid(), 'Ters Curl', 'Reverse Curl', 'pull', 'dumbbell', 'forearm extensors', 'biceps',
 'Pronated tutusla curl. On kol disi ve brachioradialisi hedefler.',
 'Curl with pronated (palm-down) grip. Targets forearm extensors.',
 ARRAY['Bilek duz','Dirsek sabit','Hafif agirlik'],
 ARRAY['Neutral wrist','Elbow fixed','Keep it light'],
 ARRAY['Bilek yukari kiriliyor','Cok agir'],
 ARRAY['Wrist hyperextension','Too heavy'],
 'intermediate'),
(gen_random_uuid(), 'Goblet Squat', 'Goblet Squat', 'legs', 'dumbbell', 'quads', 'glutes',
 'Tek dumbbelli gogus hizasinda tutup squat. Govde dik kalmasini saglar.',
 'Squat while holding a single dumbbell at chest height; encourages upright torso.',
 ARRAY['Dirsekler iceri','Govde dik','Derin in'],
 ARRAY['Elbows tucked','Torso tall','Deep descent'],
 ARRAY['Govde one egik','Yeterince derin degil'],
 ARRAY['Forward lean','Not deep enough'],
 'beginner'),
(gen_random_uuid(), 'Dumbbell Squat', 'Dumbbell Squat', 'legs', 'dumbbell', 'quads', 'glutes',
 'Dumbbelller yanlarda tutularak yapilan squat. Tutma zorluk ekler.',
 'Squat with dumbbells at the sides. Grip endurance adds loading.',
 ARRAY['Govde nispeten dik','Bilek bos','Topuktan it'],
 ARRAY['Relatively upright torso','Loose wrist','Drive through heels'],
 ARRAY['Agirliklar savruluyor','Yetersiz derinlik'],
 ARRAY['Dumbbells swinging','Shallow depth'],
 'intermediate'),
(gen_random_uuid(), 'Dumbbell Romanian Deadlift', 'Dumbbell Romanian Deadlift', 'legs', 'dumbbell', 'hamstrings', 'glutes',
 'Diz hafif bukuk, kalcayi geri it, dumbbelller bacak boyunca iner. Arka zincir.',
 'Soft knee bend, hinge hips back; dumbbells travel along the legs. Posterior chain.',
 ARRAY['Sirt duz','Arka bacak gerginligi','Kalca geri it'],
 ARRAY['Flat back','Feel hamstring stretch','Hips drive back'],
 ARRAY['Diz cok bukuluyor','Sirt yuvarlaniyor'],
 ARRAY['Too much knee bend','Rounded back'],
 'intermediate'),
(gen_random_uuid(), 'Tek Kol Row', 'Single-arm Row', 'pull', 'dumbbell', 'back', 'biceps',
 'Bir el ve diz bench uzerinde, diger kolla dumbbelli kalcaya dogru cek.',
 'Brace one hand and knee on a bench, row dumbbell with the other arm toward the hip.',
 ARRAY['Sirt duz','Dirsekten cek','Skapulayi sik'],
 ARRAY['Flat back','Lead with elbow','Squeeze scapula'],
 ARRAY['Govde donuyor','Kolla cekis'],
 ARRAY['Body rotation','Arm curling'],
 'beginner'),
(gen_random_uuid(), 'Dumbbell Lunge', 'Dumbbell Lunge', 'legs', 'dumbbell', 'quads', 'glutes',
 'Her iki elde dumbbell ile hamle. Alt vucut asimetrik yuk.',
 'Lunge while holding a dumbbell in each hand. Asymmetric lower-body loading.',
 ARRAY['On diz 90','Govde dik','Topuktan itme'],
 ARRAY['Front knee 90','Torso upright','Drive through heel'],
 ARRAY['Adim kisa','Govde egik'],
 ARRAY['Short step','Torso lean'],
 'intermediate'),
(gen_random_uuid(), 'Farmer Carry', 'Farmers Carry', 'core', 'dumbbell', 'traps', 'forearms, core',
 'Iki agir dumbbell ile duz yurume. Core, traps ve kavrama calisir.',
 'Walk in a straight line with a heavy dumbbell in each hand. Core, traps, grip.',
 ARRAY['Omuzlari geri','Govde dik','Adimlar kisa'],
 ARRAY['Shoulders back','Tall torso','Short steps'],
 ARRAY['Omuz sarkmasi','Omur-govde egilmis'],
 ARRAY['Shoulders shrugged','Leaning torso'],
 'beginner'),
(gen_random_uuid(), 'Dumbbell Calf Raise', 'Dumbbell Calf Raise', 'legs', 'dumbbell', 'calves', NULL,
 'Dumbbelllari yanda tutup paraklarla yukari kalk. Baldir calismasi.',
 'Dumbbells at sides, rise onto the balls of the feet. Calf work.',
 ARRAY['Tam uzama','Tepe sikismasi','Kontrollu iniy'],
 ARRAY['Full stretch','Peak contraction','Slow descent'],
 ARRAY['Yarim ROM','Zipla-inme'],
 ARRAY['Half ROM','Bouncing'],
 'beginner'),
-- ---- ZBAR (39-41) ----
(gen_random_uuid(), 'Z-Bar Curl', 'Z-Bar Curl', 'pull', 'zbar', 'biceps', 'forearms',
 'Z-bar ile klasik biceps curl. Bilek uyumu dumbbelllden daha iyi.',
 'Biceps curl with a Z (EZ) bar; better wrist alignment than a straight bar.',
 ARRAY['Dirsek govdede','Bilek duz','Peak sikis'],
 ARRAY['Elbows pinned','Neutral wrist','Squeeze peak'],
 ARRAY['Govde sallanmasi','Dirsek one kayiyor'],
 ARRAY['Body swing','Elbows drifting forward'],
 'intermediate'),
(gen_random_uuid(), 'Z-Bar Triceps Extension', 'Z-Bar Tricep Extension', 'push', 'zbar', 'triceps', NULL,
 'Sirt ustu bench veya ayakta Z-bar ile triceps uzama. Skull crusher varyasyonu.',
 'Lying or standing skull-crusher style tricep extension with a Z-bar.',
 ARRAY['Dirsek sabit','Yavas iniy','Alin hizasina'],
 ARRAY['Elbows fixed','Slow descent','Bar toward forehead'],
 ARRAY['Dirsek aciliyor','Asiri agir'],
 ARRAY['Flaring elbows','Too heavy'],
 'intermediate'),
(gen_random_uuid(), 'Z-Bar Upright Row', 'Z-Bar Upright Row', 'pull', 'zbar', 'lateral deltoid', 'traps',
 'Z-bar gogse dogru dirseklerden kaldir. Omuz ve trapez gelistirir.',
 'Pull a Z-bar up toward chest, leading with elbows. Deltoids and traps.',
 ARRAY['Dirsek once','Omuz hizasinda dur','Bilek notr'],
 ARRAY['Elbows first','Stop at shoulder height','Neutral wrists'],
 ARRAY['Omuza cikariyor','Omuz icten sikisiyor'],
 ARRAY['Going too high','Shoulder impingement risk'],
 'intermediate'),
-- ---- WRIST_TOOL (42-44) ----
(gen_random_uuid(), 'Bilek Curl', 'Wrist Curl', 'forearm', 'wrist_tool', 'wrist flexors', NULL,
 'Bilek aletinde veya dumbbell ile avuc yukari, bilegi bukup ac. On kol ic.',
 'Wrist curl with the forearm tool or dumbbell, palms up. Forearm flexors.',
 ARRAY['Dirsek destekli','Yavas ac-bukuk','Tam ROM'],
 ARRAY['Elbow supported','Slow open/close','Full ROM'],
 ARRAY['Cok agir','Kol hareketi'],
 ARRAY['Too heavy','Arm movement'],
 'beginner'),
(gen_random_uuid(), 'Ters Bilek Curl', 'Reverse Wrist Curl', 'forearm', 'wrist_tool', 'wrist extensors', NULL,
 'Avuc asagi bilek kivirma. On kol dis kisim calismasi.',
 'Wrist curl with palms down. Trains the forearm extensors.',
 ARRAY['Dirsek destekli','Bilek kontrol','Yumusak yuk'],
 ARRAY['Elbow supported','Control the wrist','Light load'],
 ARRAY['Cok agir','Bilek savurma'],
 ARRAY['Too heavy','Wrist flick'],
 'beginner'),
(gen_random_uuid(), 'Bilek Ruloso', 'Wrist Roller', 'forearm', 'wrist_tool', 'forearms', NULL,
 'Bilek ruloso: ipin ucundaki agirligi bileklerinle yukari sar, sonra asagi indir.',
 'Wrist roller: wind a hanging weight up and then lower it under control.',
 ARRAY['Kollari duzeltme','Yavas bildir','Dinlenme yok'],
 ARRAY['Straight arms','Slow winding','No rest mid-set'],
 ARRAY['Omuz devreye giriyor','Cok agir'],
 ARRAY['Shoulder taking over','Too heavy'],
 'intermediate'),
-- ---- BAR (pull-up bar) (45-48) ----
(gen_random_uuid(), 'Chin-up', 'Chin-up', 'pull', 'bar', 'biceps', 'back',
 'Supine tutus (avuclar sana bakan) ile barda cekis. Chin bar ustune.',
 'Pull-up with supinated (palms-toward-you) grip. Get chin over bar.',
 ARRAY['Govde kontrolu','Skapula retract','Cene bar ustunde'],
 ARRAY['Controlled body','Scapular retraction','Chin over bar'],
 ARRAY['Yarim ROM','Omuz shrug'],
 ARRAY['Half reps','Shoulders shrugged'],
 'intermediate'),
(gen_random_uuid(), 'Pull-up', 'Pull-up', 'pull', 'bar', 'lats', 'biceps',
 'Pronated tutus (avuclar disari) ile barda cekis. Geniyi sirt hedefler.',
 'Pull-up with pronated (palms-away) grip. Targets the lats.',
 ARRAY['Tam uzama','Gogus yukari','Dirsek ekseni'],
 ARRAY['Full hang','Chest up','Elbows along the body'],
 ARRAY['Govde salinimi','Yarim cekis'],
 ARRAY['Kipping','Half reps'],
 'advanced'),
(gen_random_uuid(), 'Asili Diz Cekis', 'Hanging Knee Raise', 'core', 'bar', 'abs', 'hip flexors',
 'Barda asili dururken dizleri gogse cek. Alt karin hareketleri.',
 'Hanging from a bar, draw knees to chest. Lower-ab focus.',
 ARRAY['Salinma yok','Karni sik','Yavas iniy'],
 ARRAY['No swinging','Brace abs','Slow eccentric'],
 ARRAY['Momentum kullanma','Omuz gevsek'],
 ARRAY['Using momentum','Loose shoulders'],
 'intermediate'),
(gen_random_uuid(), 'Asili Bacak Kaldirma', 'Hanging Leg Raise', 'core', 'bar', 'abs', 'hip flexors',
 'Barda asili, bacaklari duz olarak 90 dereceye kaldir. Ileri seviye karin.',
 'Hanging from a bar, raise straight legs to 90 degrees. Advanced abs.',
 ARRAY['Kontrollu inme','Bel notr','Salinma yok'],
 ARRAY['Controlled descent','Neutral spine','No swing'],
 ARRAY['Diz bukulmesi','Bel hiperekstansiyon'],
 ARRAY['Bent knees','Hyperextended lumbar'],
 'advanced'),
-- ---- MACHINE (49-50) ----
(gen_random_uuid(), 'Lat Pulldown', 'Lat Pulldown', 'pull', 'machine', 'lats', 'biceps',
 'Makine kablosunu gogse dogru cek. Geniyi sirt gelisimi.',
 'Pull the machine cable down to chest level. Lat development.',
 ARRAY['Skapula depress','Gogsu kaldir','Dirsek govde hizasi'],
 ARRAY['Scapula depressed','Lift chest','Elbows along torso line'],
 ARRAY['Bas arkasina cekme','Govde savurma'],
 ARRAY['Behind-the-neck pull','Body swing'],
 'intermediate'),
(gen_random_uuid(), 'Yuruyus', 'Walking', 'cardio', 'bodyweight', 'full body', NULL,
 'Orta tempolu yurume. Dinlenme gunu aktif recovery ve temel kardiyo.',
 'Moderate-pace walking. Active recovery and baseline cardio.',
 ARRAY['Dik dur','Adimlari kontrol et','Nefesi duzenle'],
 ARRAY['Stand tall','Controlled steps','Steady breathing'],
 ARRAY['Omuz cokmesi','Telefon bakmak'],
 ARRAY['Slumped posture','Phone gazing'],
 'beginner'),
(gen_random_uuid(), 'Bulgar Split Squat', 'Bulgarian Split Squat', 'legs', 'dumbbell', 'quads', 'glutes',
 'Arka ayak bench uzerinde tek bacakli squat. Kalca ve on bacak izolasyonu.',
 'Rear foot elevated on a bench, single-leg squat. Isolates front leg quads and glutes.',
 ARRAY['On diz topuk hizasi','Govde hafif egik','Kontrollu iniy'],
 ARRAY['Front knee over ankle','Slight torso forward','Controlled descent'],
 ARRAY['Arka diz cok savruluyor','On topuk kalkiyor'],
 ARRAY['Rear knee drifting','Front heel lifting'],
 'advanced')
) AS v(id, name_tr, name_en, category, equipment, muscle_primary, muscle_secondary,
       description_tr, description_en,
       form_tips_tr, form_tips_en,
       common_mistakes_tr, common_mistakes_en,
       difficulty)
WHERE NOT EXISTS (
    SELECT 1 FROM exercises existing WHERE LOWER(existing.name_en) = LOWER(v.name_en)
);
